### ISSUE TITLE
New namespace serviceaccount/default with automountServiceAccountToken: false

### ISSUE THREAD

**Issue by teochenglim** [open-policy-agent/gatekeeper-library#192]
For months we have been looking simple way to implement this policy, When creating a new namespace, the serviceaccount/default shall have "automountServiceAccountToken: false". Please let me know how to do it properly?

And I don't want all serviceaccount but serviceaccount: default only.

Hence the policy looks like

```yaml
apiVersion: mutations.gatekeeper.sh/v1alpha1
kind: Assign
metadata:
  name: set-automount-service-account-token-false
spec:
  applyTo:
  - groups: [""]
    kinds: ["ServiceAccount"]
    versions: ["v1"]
  match:
    scope: Namespaced
    kinds:
    - apiGroups: ["*"]
      kinds: ["ServiceAccount"]
  location: "automountServiceAccountToken"
  parameters:
    pathTests:
    - subPath: "metadata[name: default]"
      condition: MustExist
    assign:
      value: false

```

However I get a logical block code 422, and I just want to know why you make it less powerful?

{"kind":"Status","apiVersion":"v1","metadata":{},"status":"Failure","message":"admission webhook \"validation.gatekeeper.sh\" denied the request: all subpaths must be a prefix of the `location` value of the mutation: subpath \"metadata[name: *]\" 

```shell
hTests":[{"condition":"MustNotExist","subPath":"metadata[name: *]"}]}}}
I0425 13:48:51.630800   28794 round_trippers.go:466] curl -v -XPATCH  -H "User-Agent: kubectl/v1.23.6 (darwin/amd64) kubernetes/ad33385" -H "Accept: application/json" -H "Content-Type: application/merge-patch+json" 'https://127.0.0.1:6443/apis/mutations.gatekeeper.sh/v1alpha1/assign/set-automount-service-account-token-false?fieldManager=kubectl-client-side-apply'
I0425 13:48:51.668248   28794 round_trippers.go:570] HTTP Statistics: GetConnection 0 ms ServerProcessing 37 ms Duration 37 ms
I0425 13:48:51.668271   28794 round_trippers.go:577] Response Headers:
I0425 13:48:51.668278   28794 round_trippers.go:580]     Cache-Control: no-cache, private
I0425 13:48:51.668283   28794 round_trippers.go:580]     Content-Type: application/json
I0425 13:48:51.668288   28794 round_trippers.go:580]     Audit-Id: 27182809-b4fc-43df-befc-7caebe987575
I0425 13:48:51.668293   28794 round_trippers.go:580]     X-Kubernetes-Pf-Flowschema-Uid: 901207e3-5528-49e6-9d46-4f9cfd79cd7a
I0425 13:48:51.668298   28794 round_trippers.go:580]     X-Kubernetes-Pf-Prioritylevel-Uid: c19aa718-826a-4b17-8f08-3475c0fd8d8e
I0425 13:48:51.668303   28794 round_trippers.go:580]     Date: Mon, 25 Apr 2022 05:48:49 GMT
I0425 13:48:51.668307   28794 round_trippers.go:580]     Content-Length: 321
I0425 13:48:51.668347   28794 request.go:1181] Response Body: {"kind":"Status","apiVersion":"v1","metadata":{},"status":"Failure","message":"admission webhook \"validation.gatekeeper.sh\" denied the request: all subpaths must be a prefix of the `location` value of the mutation: subpath \"metadata[name: *]\" is not a prefix of location \"automountServiceAccountToken\"","code":422}
F0425 13:48:51.671490   28794 helpers.go:118] The request is invalid
goroutine 1 [running]:
k8s.io/kubernetes/vendor/k8s.io/klog/v2.stacks(0x1)
	/private/tmp/kubernetes-cli-20220420-25205-aqgeag/_output/local/go/src/k8s.io/kubernetes/vendor/k8s.io/klog/v2/klog.go:1038 +0x8a
k8s.io/kubernetes/vendor/k8s.io/klog/v2.(*loggingT).output(0x6ce6640, 0x3, 0x0, 0xc00143e380, 0x2, {0x62fde2a?, 0x8140a68?}, 0x10?, 0x0)
	/private/tmp/kubernetes-cli-20220420-25205-aqgeag/_output/local/go/src/k8s.io/kubernetes/vendor/k8s.io/klog/v2/klog.go:987 +0x5fd
k8s.io/kubernetes/vendor/k8s.io/klog/v2.(*loggingT).printDepth(0x58e43b3?, 0x16?, 0x0, {0x0, 0x0}, 0x1a6?, {0xc000a79220?, 0x1, 0x1})
	/private/tmp/kubernetes-cli-20220420-25205-aqgeag/_output/local/go/src/k8s.io/kubernetes/vendor/k8s.io/klog/v2/klog.go:735 +0x1c5
k8s.io/kubernetes/vendor/k8s.io/klog/v2.FatalDepth(...)
```

**Comment by maxsmythe** [comment]
You should be able to write this using `match.name` (sorry it doesn't look like the name matcher is documented):

```
apiVersion: mutations.gatekeeper.sh/v1alpha1
kind: Assign
metadata:
  name: set-automount-service-account-token-false
spec:
  applyTo:
  - groups: [""]
    kinds: ["ServiceAccount"]
    versions: ["v1"]
  match:
    scope: Namespaced
    name: "default"
    kinds:
    - apiGroups: ["*"]
      kinds: ["ServiceAccount"]
  location: "automountServiceAccountToken"
  parameters:
    assign:
      value: false
```

The reason for disallowing pathtests other than against the path-to-be-mutated is to avoid situations where users can create infinite recursion. The risk is described in this doc:

https://docs.google.com/document/d/1WKj-9xYYVO9IckQVZHYVFCziRVS6zxCfvJxWbkbLcOM/view#heading=h.clbtrv5230v8

**Comment by teochenglim** [comment]
Cool! That's super help and it does the job. Thank you very much.
